<?php
	$partners   = array();
	$partners[] = array(
		'short' => 'ACLA',
		'title' => 'Allegheny County Library Association',
		'url'   => 'http://www.aclalibraries.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/ACLA-for-web1.png',);
	$partners[] = array(
		'short' => 'AIU',
		'title' => 'Allegheny Intermediate Unit',
		'url'   => 'http://www.aiu3.net/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/AIU3.png',);
	$partners[] = array(
		'short' => 'APOST',
		'title' => 'Allegheny Partners for Out-of-School Time',
		'url'   => 'http://www.afterschoolpgh.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/10/APOSTlogo1.jpg',);
	$partners[] = array(
		'short' => 'Carnegie Library',
		'title' => 'Carnegie Library of Pittsburgh',
		'url'   => 'http://www.carnegielibrary.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/06/clplogobig.jpg',);
	$partners[] = array(
		'short' => 'Carnegie Mellon',
		'title' => 'Carnegie Mellon University',
		'url'   => 'http://www.cmu.edu/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/CMU.jpg',);
	$partners[] = array(
		'short' => 'Carnegie Museums',
		'title' => 'Carnegie Museums of Pittsburgh',
		'url'   => 'http://www.carnegiemuseums.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/carnegie-dippy.jpg',);
	$partners[] = array(
		'short' => 'Children’s Museum',
		'title' => 'Children’s Museum of Pittsburgh',
		'url'   => 'https://pittsburghkids.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/Childrens-Museum-of-Pittsburgh.png',);
	$partners[] = array(
		'short' => 'Common Sense Media',
		'title' => 'Common Sense Media',
		'url'   => 'https://www.commonsensemedia.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/08/common-sense-for-web.jpg',);
	$partners[] = array(
		'short' => 'CLA',
		'title' => 'Connected Learning Alliance',
		'url'   => 'http://clalliance.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/10/cla.png',);
	$partners[] = array(
		'short' => 'CREATE Lab',
		'title' => 'CREATE Lab at Carnegie Mellon',
		'url'   => 'http://www.cmucreatelab.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/05/CREATE_logo.jpg',);
	$partners[] = array(
		'short' => 'ETC',
		'title' => 'Entertainment Technology Center at Carnegie Mellon',
		'url'   => 'http://www.etc.cmu.edu/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/10/etc-3x2.png',);
	$partners[] = array(
		'short' => 'Fred Rogers Center',
		'title' => 'Fred Rogers Center at St. Vincent College',
		'url'   => 'http://www.fredrogerscenter.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/03/Fred-Rogers-Center-e1362595258546.png',);
	$partners[] = array(
		'short' => 'Fred Rogers Company',
		'title' => 'The Fred Rogers Company',
		'url'   => 'http://www.fredrogers.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/FRC.png',);
	$partners[] = array(
		'short' => 'Hive Global',
		'title' => 'Hive Learning Networks',
		'url'   => 'http://hivelearningnetworks.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/Hive.png',);
	$partners[] = array(
		'short' => 'Idea Foundry',
		'title' => 'Idea Foundry',
		'url'   => 'http://ideafoundry.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/10/ideafoundry.png',);
	$partners[] = array(
		'short' => 'Kidsburgh',
		'title' => 'Kidsburgh',
		'url'   => 'http://www.kidsburgh.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/10/Kidsburgh_VertLogo_CMYK.png',);
	$partners[] = array(
		'short' => 'LRDC',
		'title' => 'Learning Research and Development Center ',
		'url'   => 'http://www.lrdc.pitt.edu/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/01/LRDCBUILDING2.jpg',);
	$partners[] = array(
		'short' => 'Maker Ed',
		'title' => 'Maker Education Initiative',
		'url'   => 'http://makered.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/10/makered.png',);
	$partners[] = array(
		'short' => 'Mozilla',
		'title' => 'Mozilla',
		'url'   => 'https://www.mozilla.org/en-US/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/10/wordmark.jpg',);
	$partners[] = array(
		'short' => 'NEXTpittsburgh',
		'title' => 'NEXTpittsburgh',
		'url'   => 'http://www.nextpittsburgh.com/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/10/NEXT-Logo-FullColor1.png',);
	$partners[] = array(
		'short' => 'PAEYC',
		'title' => 'Pittsburgh Association for the Education of Young Children',
		'url'   => 'http://www.paeyc.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/07/PAEYC-logo1.jpg',);
	$partners[] = array(
		'short' => 'PBS',
		'title' => 'PBS Learning Media',
		'url'   => 'http://www.pbslearningmedia.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/10/PBS_LearningMedia_Logo.png',);
	$partners[] = array(
		'short' => 'Pittsburgh Magazine',
		'title' => 'Pittsburgh Magazine',
		'url'   => 'http://www.pittsburghmagazine.com/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/10/pittsburghmagazine-logo.jpg',);
	$partners[] = array(
		'short' => 'Tech Council',
		'title' => 'Pittsburgh Technology Council',
		'url'   => 'http://www.pghtech.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/PittsburghTechnologyCouncil_red_stacked.png',);
	$partners[] = array(
		'short' => 'Remake Learning Council',
		'title' => 'Remake Learning Council',
		'url'   => 'http://remakelearning.org/organization/remake-learning-council/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/10/RML-council-1600x2400px.png',);
	$partners[] = array(
		'short' => 'Sprout',
		'title' => 'The Sprout Fund',
		'url'   => 'http://www.sproutfund.org',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/Sprout-Fund.png',);
	$partners[] = array(
		'short' => 'Steeltown',
		'title' => 'Steeltown Entertainment Project',
		'url'   => 'http://www.steeltown.org',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2014/05/steeltown-logo.jpg',);
	$partners[] = array(
		'short' => 'Tech Shop',
		'title' => 'Tech Shop Pittsburgh',
		'url'   => 'http://www.techshop.ws/pittsburgh.html',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/07/techshop_logo_main-page-001-690x460.jpg',);
	$partners[] = array(
		'short' => 'Univ of Pitt',
		'title' => 'University of Pittsburgh',
		'url'   => 'http://www.pitt.edu/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/06/pitt-e1371655192798.png',);
	$partners[] = array(
		'short' => 'WESA',
		'title' => '90.5 WESA',
		'url'   => 'http://wesa.fm/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/07/wesa-large-logo1.jpg',);
	$partners[] = array(
		'short' => 'WQED',
		'title' => 'WQED Multimedia',
		'url'   => 'http://www.wqed.org/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/WQED.jpg',);
	$partners[] = array(
		'short' => 'Zulama',
		'title' => 'Zulama',
		'url'   => 'http://zulama.com/',
		'logo'  => 'http://cloudfront.sproutfund.org/files/2013/02/Spark-Org-Logo-Template.png',);
?>
<?php if( !empty($partners) ) : ?>
	<ul class="large-block-grid-4 medium-block-grid-4 small-block-grid-2">
		<?php foreach( $partners as $partner ) : ?>
			<li><!--<?php echo $partner['short']; ?>-->
				<a title="<?php echo $partner['title']; ?>" href="<?php echo $partner['url']; ?>" target="_blank">
					<img src="<?php echo $partner['logo']; ?>" style="clear: both;">
				</a>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>